# Generated by Django 2.1.1 on 2018-10-09 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catone', '0002_auto_20180914_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='catone_papers',
            name='relative_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
