# Generated by Django 2.2.8 on 2019-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catone', '0004_auto_20191205_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_portal',
            name='correct_option',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz_portal',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz_portal',
            name='options',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz_portal',
            name='quiz',
            field=models.CharField(max_length=500),
        ),
    ]
